name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Gerar snake padrão (modo claro)
      - name: Generate Snake (Light)
        uses: Platane/snk@v3
        with:
          github_user_name: elieber-fernandes
          outputs: dist/github-contribution-grid-snake.svg

      # Gerar snake modo escuro
      - name: Generate Snake (Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: elieber-fernandes
          dark_mode: true
          outputs: dist/github-contribution-grid-snake-dark.svg

      # Publicar na branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
